ALTER TABLE loads ADD COLUMN IF NOT EXISTS origin_lat FLOAT;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS origin_lon FLOAT;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS destination_lat FLOAT;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS destination_lon FLOAT;
